name: cd-dev-wf
on:
  push:
    branches:
      - main
jobs:
  deploy-dev-job:
    runs-on: ubuntu-latest
    environment: "Production-env"
    steps:
      - name: Welcome to Dev-Cd
        run: echo "Your app is goint to be deployeed at render.com"
      - name: Deploye Appp
        run: curl -X POST ${{secrets.RENDER_CALLBACK_URL}}
