name: Cd file for staging 
on:
   push:
     branches:
      - develop
      - main
jobs:
  staging_job:
    runs-on: ubuntu-latest
    environment: staging-env
    steps:
     - name: Trigger web hook for staging enviornment
       run: curl -X POST ${{secrets.STAGING_RENDER_HOOK}}

